# Generated by Django 5.2.5 on 2025-09-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Convocacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("titulo", models.CharField(max_length=200)),
                ("numero", models.CharField(max_length=50, unique=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("concurso", "Concurso Público"),
                            ("processo_seletivo", "Processo Seletivo"),
                            ("chamada_publica", "Chamada Pública"),
                            ("edital", "Edital"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descricao", models.TextField()),
                ("data_publicacao", models.DateTimeField(blank=True, null=True)),
                ("data_inicio_inscricoes", models.DateTimeField(blank=True, null=True)),
                ("data_fim_inscricoes", models.DateTimeField(blank=True, null=True)),
                ("data_inicio_provas", models.DateTimeField(blank=True, null=True)),
                ("data_fim_provas", models.DateTimeField(blank=True, null=True)),
                ("data_resultado", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("publicada", "Publicada"),
                            ("em_andamento", "Em Andamento"),
                            ("finalizada", "Finalizada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="rascunho",
                        max_length=20,
                    ),
                ),
                ("vagas_disponiveis", models.PositiveIntegerField(default=0)),
                ("requisitos", models.TextField(blank=True)),
                ("documentos_necessarios", models.TextField(blank=True)),
                ("observacoes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Convocação",
                "verbose_name_plural": "Convocações",
                "ordering": ["-data_publicacao", "titulo"],
            },
        ),
    ]
